# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Home Kit.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 600)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 350))
        MainWindow.setMaximumSize(QtCore.QSize(1024, 600))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("""font-family: Poppins; 
                                 QPushButton 
                                {
                                        outline: none; /* Remove the dashed border */
                                }
                                QPushButton:focus {
                                         outline: none; /* Ensure it's not shown on focus */
                                }
                                
""")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 58))
        self.frame.setStyleSheet("background: black;\n"
"padding: 0 px; \n"
"border: 0 px; \n"
"margin: 0 px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Home = QtWidgets.QLabel(self.frame)
        self.Home.setMinimumSize(QtCore.QSize(77, 24))
        self.Home.setStyleSheet("color: white; \n"
"font-size: 16px;\n"
"font-weight:600;\n"
"line-height:24px;\n"
"padding-left:6px;\n"
"")
        self.Home.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Home.setObjectName("Home")
        self.horizontalLayout.addWidget(self.Home)
        self.space_2 = QtWidgets.QLabel(self.frame)
        self.space_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.space_2.setStyleSheet("padding:0px; margin:0px;")
        self.space_2.setText("")
        self.space_2.setAlignment(QtCore.Qt.AlignCenter)
        self.space_2.setObjectName("space_2")
        self.horizontalLayout.addWidget(self.space_2)
        self.automaiton = QtWidgets.QToolButton(self.frame)
        self.automaiton.setMinimumSize(QtCore.QSize(197, 37))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setBold(True)
        font.setWeight(62)
        self.automaiton.setFont(font)
        self.automaiton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.automaiton.setStyleSheet("color: white;\n"
"font-family: Poppins;\n"
"font-size: 14px;\n"
"font-weight: 500;\n"
"line-height: 21px;\n"
"padding: 0px 14px 0px 14px;\n"
"border-radius: 10px 0px 0px 0px;\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/addtional_icons/resources/addtional_icons/Alarm Light.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.automaiton.setIcon(icon)
        self.automaiton.setIconSize(QtCore.QSize(24, 24))
        self.automaiton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.automaiton.setObjectName("automaiton")
        self.horizontalLayout.addWidget(self.automaiton)
        self.space = QtWidgets.QLabel(self.frame)
        self.space.setStyleSheet("padding:0px; margin:0px;")
        self.space.setText("")
        self.space.setAlignment(QtCore.Qt.AlignCenter)
        self.space.setObjectName("space")
        self.horizontalLayout.addWidget(self.space)
        self.add_button = QtWidgets.QToolButton(self.frame)
        self.add_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.add_button.setStyleSheet("")
        self.add_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/addtional_icons/resources/addtional_icons/Plus Light.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.add_button.setIcon(icon1)
        self.add_button.setIconSize(QtCore.QSize(48, 48))
        self.add_button.setObjectName("add_button")
        self.horizontalLayout.addWidget(self.add_button)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("background: black; \n"
"border: 0px; \n"
"padding: 0px; \n"
"margin: 0px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(1)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setStyleSheet("")
        self.page.setObjectName("page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.container = QtWidgets.QWidget()
        self.container.setGeometry(QtCore.QRect(0, 197, 1024, 154))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.container.sizePolicy().hasHeightForWidth())
        self.container.setSizePolicy(sizePolicy)
        self.container.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.container.setStyleSheet("")
        self.container.setObjectName("container")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.container)
        self.verticalLayout_2.setContentsMargins(80, -1, 80, -1)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
     
        self.scrollArea.setWidget(self.container)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(-10, 0, 1011, 531))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_3 = QtWidgets.QLabel(self.page_3)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 981, 511))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_4 = QtWidgets.QLabel(self.page_4)
        self.label_4.setGeometry(QtCore.QRect(10, 0, 991, 511))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        self.label_4.setFont(font)
        self.label_4.setScaledContents(False)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setOpenExternalLinks(False)
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.page_4)
        self.verticalLayout_4.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Home.setText(_translate("MainWindow", "My Home"))
        self.automaiton.setText(_translate("MainWindow", "  Automations"))
        self.label_2.setText(_translate("MainWindow", "This will be second page"))
        self.label_3.setText(_translate("MainWindow", "This is the Third page"))
        self.label_4.setText(_translate("MainWindow", "This will be fourth page"))
import resource_files_rc
